eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  eureka:
    instance:
      hostname:  localhost 
 
 
 microservice:
  payment-servicee:
    endpoints:
      endpoint:
         uri: http://PAYMENT-SERVICEE/payment/dopayment
  order-service:
   endpoints:
      endpoint:
         uri: http://ORDER-SERVICEE/order/bookOrder
